FROM docker.io/maven:3.9.0-eclipse-temurin-17-focal AS build
WORKDIR /app
ENV REGISTRY_HOST=localhost
ENV REGISTRY_PORT=8761
ENV SERVER_PORT=43210
COPY . .
RUN mvn install || true
RUN find /app/src/main/java -type f -name '*.java' -exec sed -i 's/javax/jakarta/g' {} +
RUN mvn package

FROM docker.io/eclipse-temurin:17-jdk-alpine
COPY --from=build /app/target/app.jar app.jar
ENTRYPOINT [ "java", "-jar", "app.jar" ]
