//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.18 at 06:44:09 PM COT 
//


package co.edu.javeriana.ms.calificacion.entities;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SearchResultsDTO" type="{http://ms.javeriana.edu.co/Calificacion/entities}searchResultsDTO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchResultsDTO"
})
@XmlRootElement(name = "buscarProductosResponse")
public class BuscarProductosResponse {

    @XmlElement(name = "SearchResultsDTO", required = true)
    protected SearchResultsDTO searchResultsDTO;

    /**
     * Gets the value of the searchResultsDTO property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResultsDTO }
     *     
     */
    public SearchResultsDTO getSearchResultsDTO() {
        return searchResultsDTO;
    }

    /**
     * Sets the value of the searchResultsDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResultsDTO }
     *     
     */
    public void setSearchResultsDTO(SearchResultsDTO value) {
        this.searchResultsDTO = value;
    }

}
