//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.18 at 06:44:09 PM COT 
//


package co.edu.javeriana.ms.calificacion.entities;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.edu.javeriana.ms.calificacion.entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.edu.javeriana.ms.calificacion.entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchResultsDTO }
     * 
     */
    public SearchResultsDTO createSearchResultsDTO() {
        return new SearchResultsDTO();
    }

    /**
     * Create an instance of {@link BuscarProductosRequest }
     * 
     */
    public BuscarProductosRequest createBuscarProductosRequest() {
        return new BuscarProductosRequest();
    }

    /**
     * Create an instance of {@link BuscarProductosResponse }
     * 
     */
    public BuscarProductosResponse createBuscarProductosResponse() {
        return new BuscarProductosResponse();
    }

    /**
     * Create an instance of {@link Servicio }
     * 
     */
    public Servicio createServicio() {
        return new Servicio();
    }

    /**
     * Create an instance of {@link Contenido }
     * 
     */
    public Contenido createContenido() {
        return new Contenido();
    }

    /**
     * Create an instance of {@link Proveedor }
     * 
     */
    public Proveedor createProveedor() {
        return new Proveedor();
    }

    /**
     * Create an instance of {@link Cliente }
     * 
     */
    public Cliente createCliente() {
        return new Cliente();
    }

    /**
     * Create an instance of {@link InfoAdicional }
     * 
     */
    public InfoAdicional createInfoAdicional() {
        return new InfoAdicional();
    }

    /**
     * Create an instance of {@link SearchResultsDTO.Servicios }
     * 
     */
    public SearchResultsDTO.Servicios createSearchResultsDTOServicios() {
        return new SearchResultsDTO.Servicios();
    }

}
