//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.18 at 06:44:09 PM COT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ms.javeriana.edu.co/Calificacion/entities", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.edu.javeriana.ms.calificacion.entities;
