# This compose file uses images and needs no extern attention
services:
  # API Gateway
  service-discovery:
    image: docker.io/micr0nclsbayona/api-gateway-serviced
    environment:
      - SERVER_PORT=8761
    ports:
      - "8000:8761"
  
  auth-service:
    image: docker.io/micr0nclsbayona/api-gateway-auth
    environment:
      - REGISTRY_HOST=service-discovery
      - REGISTRY_PORT=8761
      - SERVER_PORT=8080

  load-balancer:
    image: docker.io/micr0nclsbayona/api-gateway-loadbalancer
    ports:
      - 8001:8080
    environment:
      - REGISTRY_HOST=service-discovery
      - REGISTRY_PORT=8761
      - SERVER_PORT=8080

  # Microservices
  search_soap-service:
    image: docker.io/micr0nclsbayona/microservices-soaps
    environment:
      - REGISTRY_HOST=service-discovery
      - REGISTRY_PORT=8761
      - SERVER_PORT=8080

  grades-service:
    image: docker.io/micr0nclsbayona/microservices-grades
    environment:
      - REGISTRY_HOST=service-discovery
      - REGISTRY_PORT=8761
      - SERVER_PORT=8080

  purchases-service:
    image: docker.io/micr0nclsbayona/microservices-purchases
    environment:
      - REGISTRY_HOST=service-discovery
      - REGISTRY_PORT=8761
      - SERVER_PORT=8080
    env_file:
      - purchases_api_keys.env

  products-service:
    image: docker.io/micr0nclsbayona/microservices-products
    environment:
      - REGISTRY_HOST=service-discovery
      - REGISTRY_PORT=8761
      - SERVER_PORT=8080
    env_file:
      - service_api_keys.env
      
   # Client
  client:
    image: docker.io/micr0nclsbayona/client
    environment:
      - GATEWAY_IP=load-balancer:8080
