FROM docker.io/maven:3.9.0-eclipse-temurin-17-focal AS build
WORKDIR /app
ENV REGISTRY_HOST=localhost
ENV REGISTRY_PORT=8761
ENV SERVER_PORT=8080
COPY . .
RUN mvn clean install compile && mvn clean package

FROM docker.io/eclipse-temurin:17-jdk-alpine
COPY --from=build /app/target/app.jar app.jar
ENTRYPOINT [ "java", "-jar", "app.jar" ]
