//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.18 at 06:44:09 PM COT 
//


package co.edu.javeriana.ms.calificacion.entities;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for searchResultsDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="searchResultsDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="servicios"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="servicio" type="{http://ms.javeriana.edu.co/Calificacion/entities}servicio"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchResultsDTO", propOrder = {
    "servicios"
})
public class SearchResultsDTO {

    @XmlElement(required = true)
    protected SearchResultsDTO.Servicios servicios;

    /**
     * Gets the value of the servicios property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResultsDTO.Servicios }
     *     
     */
    public SearchResultsDTO.Servicios getServicios() {
        return servicios;
    }

    /**
     * Sets the value of the servicios property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResultsDTO.Servicios }
     *     
     */
    public void setServicios(SearchResultsDTO.Servicios value) {
        this.servicios = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="servicio" type="{http://ms.javeriana.edu.co/Calificacion/entities}servicio"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "servicio"
    })
    public static class Servicios {

        @XmlElement(required = true)
        protected Servicio servicio;

        /**
         * Gets the value of the servicio property.
         * 
         * @return
         *     possible object is
         *     {@link Servicio }
         *     
         */
        public Servicio getServicio() {
            return servicio;
        }

        /**
         * Sets the value of the servicio property.
         * 
         * @param value
         *     allowed object is
         *     {@link Servicio }
         *     
         */
        public void setServicio(Servicio value) {
            this.servicio = value;
        }

    }

}
